# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          set -xe && apt update && apt install python3-pip -y
          python3 -m pip install pip==21.1.2 pipenv==2021.5.29
          python3 -m pip --version
          python3 -m pip install .
      - name: Tests and Coverage
        run: |
          cov=$(pytest --cov=nempy | grep TOTAL | grep -Eo '[0-9]+%')
          echo $cov
          echo "COVERAGE=$cov" >> $GITHUB_ENV
      # Runs a set of commands using the runners shell
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 9c7a615b3b16ced41d8530c7535ca131
          filename: coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}
          color: dodgerblue
